// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: contracts/orchestrator.proto

package events

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NormalizedEvent corresponds to events.normalized
type NormalizedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Severity      string                 `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`
	RawPayload    *structpb.Struct       `protobuf:"bytes,5,opt,name=raw_payload,json=rawPayload,proto3" json:"raw_payload,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NormalizedEvent) Reset() {
	*x = NormalizedEvent{}
	mi := &file_contracts_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NormalizedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalizedEvent) ProtoMessage() {}

func (x *NormalizedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalizedEvent.ProtoReflect.Descriptor instead.
func (*NormalizedEvent) Descriptor() ([]byte, []int) {
	return file_contracts_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *NormalizedEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *NormalizedEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *NormalizedEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *NormalizedEvent) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *NormalizedEvent) GetRawPayload() *structpb.Struct {
	if x != nil {
		return x.RawPayload
	}
	return nil
}

func (x *NormalizedEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// DomainEvent corresponds to events.k8s, events.db etc.
type DomainEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EventId          string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Domain           string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"` // k8s, infra, db
	ClusterId        string                 `protobuf:"bytes,3,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	ServiceName      string                 `protobuf:"bytes,4,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	RelatedResources []string               `protobuf:"bytes,5,rep,name=related_resources,json=relatedResources,proto3" json:"related_resources,omitempty"`
	Metrics          *structpb.Struct       `protobuf:"bytes,6,opt,name=metrics,proto3" json:"metrics,omitempty"`
	OriginalEvent    *NormalizedEvent       `protobuf:"bytes,7,opt,name=original_event,json=originalEvent,proto3" json:"original_event,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DomainEvent) Reset() {
	*x = DomainEvent{}
	mi := &file_contracts_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainEvent) ProtoMessage() {}

func (x *DomainEvent) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainEvent.ProtoReflect.Descriptor instead.
func (*DomainEvent) Descriptor() ([]byte, []int) {
	return file_contracts_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *DomainEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *DomainEvent) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DomainEvent) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *DomainEvent) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *DomainEvent) GetRelatedResources() []string {
	if x != nil {
		return x.RelatedResources
	}
	return nil
}

func (x *DomainEvent) GetMetrics() *structpb.Struct {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *DomainEvent) GetOriginalEvent() *NormalizedEvent {
	if x != nil {
		return x.OriginalEvent
	}
	return nil
}

// Decision corresponds to decisions.*
type Decision struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DecisionId      string                 `protobuf:"bytes,1,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	IncidentId      string                 `protobuf:"bytes,2,opt,name=incident_id,json=incidentId,proto3" json:"incident_id,omitempty"`
	Analysis        string                 `protobuf:"bytes,3,opt,name=analysis,proto3" json:"analysis,omitempty"`
	ProposedActions []*Action              `protobuf:"bytes,4,rep,name=proposed_actions,json=proposedActions,proto3" json:"proposed_actions,omitempty"`
	ConfidenceScore float64                `protobuf:"fixed64,5,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Decision) Reset() {
	*x = Decision{}
	mi := &file_contracts_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decision) ProtoMessage() {}

func (x *Decision) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decision.ProtoReflect.Descriptor instead.
func (*Decision) Descriptor() ([]byte, []int) {
	return file_contracts_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *Decision) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *Decision) GetIncidentId() string {
	if x != nil {
		return x.IncidentId
	}
	return ""
}

func (x *Decision) GetAnalysis() string {
	if x != nil {
		return x.Analysis
	}
	return ""
}

func (x *Decision) GetProposedActions() []*Action {
	if x != nil {
		return x.ProposedActions
	}
	return nil
}

func (x *Decision) GetConfidenceScore() float64 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

// Action represents a proposed or approved action
type Action struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionId      string                 `protobuf:"bytes,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	DecisionId    string                 `protobuf:"bytes,2,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	ActionType    string                 `protobuf:"bytes,3,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	Target        string                 `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	Params        map[string]string      `protobuf:"bytes,5,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Reasoning     string                 `protobuf:"bytes,6,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
	Approver      string                 `protobuf:"bytes,7,opt,name=approver,proto3" json:"approver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_contracts_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_contracts_orchestrator_proto_rawDescGZIP(), []int{3}
}

func (x *Action) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *Action) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *Action) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *Action) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Action) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Action) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

func (x *Action) GetApprover() string {
	if x != nil {
		return x.Approver
	}
	return ""
}

// ActionStatus corresponds to actions.status
type ActionStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionId      string                 `protobuf:"bytes,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionStatus) Reset() {
	*x = ActionStatus{}
	mi := &file_contracts_orchestrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionStatus) ProtoMessage() {}

func (x *ActionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_orchestrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionStatus.ProtoReflect.Descriptor instead.
func (*ActionStatus) Descriptor() ([]byte, []int) {
	return file_contracts_orchestrator_proto_rawDescGZIP(), []int{4}
}

func (x *ActionStatus) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *ActionStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ActionStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ActionStatus) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_contracts_orchestrator_proto protoreflect.FileDescriptor

const file_contracts_orchestrator_proto_rawDesc = "" +
	"\n" +
	"\x1ccontracts/orchestrator.proto\x12\x15incident.orchestrator\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xe3\x02\n" +
	"\x0fNormalizedEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\x128\n" +
	"\vraw_payload\x18\x05 \x01(\v2\x17.google.protobuf.StructR\n" +
	"rawPayload\x12P\n" +
	"\bmetadata\x18\x06 \x03(\v24.incident.orchestrator.NormalizedEvent.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb1\x02\n" +
	"\vDomainEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x03 \x01(\tR\tclusterId\x12!\n" +
	"\fservice_name\x18\x04 \x01(\tR\vserviceName\x12+\n" +
	"\x11related_resources\x18\x05 \x03(\tR\x10relatedResources\x121\n" +
	"\ametrics\x18\x06 \x01(\v2\x17.google.protobuf.StructR\ametrics\x12M\n" +
	"\x0eoriginal_event\x18\a \x01(\v2&.incident.orchestrator.NormalizedEventR\roriginalEvent\"\xdd\x01\n" +
	"\bDecision\x12\x1f\n" +
	"\vdecision_id\x18\x01 \x01(\tR\n" +
	"decisionId\x12\x1f\n" +
	"\vincident_id\x18\x02 \x01(\tR\n" +
	"incidentId\x12\x1a\n" +
	"\banalysis\x18\x03 \x01(\tR\banalysis\x12H\n" +
	"\x10proposed_actions\x18\x04 \x03(\v2\x1d.incident.orchestrator.ActionR\x0fproposedActions\x12)\n" +
	"\x10confidence_score\x18\x05 \x01(\x01R\x0fconfidenceScore\"\xb7\x02\n" +
	"\x06Action\x12\x1b\n" +
	"\taction_id\x18\x01 \x01(\tR\bactionId\x12\x1f\n" +
	"\vdecision_id\x18\x02 \x01(\tR\n" +
	"decisionId\x12\x1f\n" +
	"\vaction_type\x18\x03 \x01(\tR\n" +
	"actionType\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x12A\n" +
	"\x06params\x18\x05 \x03(\v2).incident.orchestrator.Action.ParamsEntryR\x06params\x12\x1c\n" +
	"\treasoning\x18\x06 \x01(\tR\treasoning\x12\x1a\n" +
	"\bapprover\x18\a \x01(\tR\bapprover\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x93\x01\n" +
	"\fActionStatus\x12\x1b\n" +
	"\taction_id\x18\x01 \x01(\tR\bactionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestampB=Z;github.com/ChiragJS/IncidentResponseOrchestrator/pkg/eventsb\x06proto3"

var (
	file_contracts_orchestrator_proto_rawDescOnce sync.Once
	file_contracts_orchestrator_proto_rawDescData []byte
)

func file_contracts_orchestrator_proto_rawDescGZIP() []byte {
	file_contracts_orchestrator_proto_rawDescOnce.Do(func() {
		file_contracts_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contracts_orchestrator_proto_rawDesc), len(file_contracts_orchestrator_proto_rawDesc)))
	})
	return file_contracts_orchestrator_proto_rawDescData
}

var file_contracts_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_contracts_orchestrator_proto_goTypes = []any{
	(*NormalizedEvent)(nil),       // 0: incident.orchestrator.NormalizedEvent
	(*DomainEvent)(nil),           // 1: incident.orchestrator.DomainEvent
	(*Decision)(nil),              // 2: incident.orchestrator.Decision
	(*Action)(nil),                // 3: incident.orchestrator.Action
	(*ActionStatus)(nil),          // 4: incident.orchestrator.ActionStatus
	nil,                           // 5: incident.orchestrator.NormalizedEvent.MetadataEntry
	nil,                           // 6: incident.orchestrator.Action.ParamsEntry
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 8: google.protobuf.Struct
}
var file_contracts_orchestrator_proto_depIdxs = []int32{
	7, // 0: incident.orchestrator.NormalizedEvent.timestamp:type_name -> google.protobuf.Timestamp
	8, // 1: incident.orchestrator.NormalizedEvent.raw_payload:type_name -> google.protobuf.Struct
	5, // 2: incident.orchestrator.NormalizedEvent.metadata:type_name -> incident.orchestrator.NormalizedEvent.MetadataEntry
	8, // 3: incident.orchestrator.DomainEvent.metrics:type_name -> google.protobuf.Struct
	0, // 4: incident.orchestrator.DomainEvent.original_event:type_name -> incident.orchestrator.NormalizedEvent
	3, // 5: incident.orchestrator.Decision.proposed_actions:type_name -> incident.orchestrator.Action
	6, // 6: incident.orchestrator.Action.params:type_name -> incident.orchestrator.Action.ParamsEntry
	7, // 7: incident.orchestrator.ActionStatus.timestamp:type_name -> google.protobuf.Timestamp
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_contracts_orchestrator_proto_init() }
func file_contracts_orchestrator_proto_init() {
	if File_contracts_orchestrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contracts_orchestrator_proto_rawDesc), len(file_contracts_orchestrator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contracts_orchestrator_proto_goTypes,
		DependencyIndexes: file_contracts_orchestrator_proto_depIdxs,
		MessageInfos:      file_contracts_orchestrator_proto_msgTypes,
	}.Build()
	File_contracts_orchestrator_proto = out.File
	file_contracts_orchestrator_proto_goTypes = nil
	file_contracts_orchestrator_proto_depIdxs = nil
}
